- name: Build an setup machine tokens env
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Build MIS app
      containers.podman.podman_image:
        name: mis
        path: "{{ playbook_dir }}"
        force: true
        build:
          format: oci

    - name: Generate pod yml
      ansible.builtin.template:
        src: pod.yml.j2
        dest: pod.yml
      vars:
        mis_image: "localhost/mis:latest"
        realm_import_dir: "{{ playbook_dir }}/realm"
        mis_container_port: 8081
        client_id: vault
        client_secret: vault
        username: cosmin
        password: cosmin
        vault_init_script: init_vault.sh
        vault_init_dir: "{{ playbook_dir }}"

    - name: Start pod
      containers.podman.podman_play:
        kube_file: pod.yml
        state: started

    - name: Wait for Vault to initialize
      ansible.builtin.wait_for:
        timeout: 5

    - name: Init vault
      containers.podman.podman_container_exec:
        name: machine_tokens-vault
        command: "/bin/sh -c /init_vault.sh"
        workdir: /
