apiVersion: v1
kind: Pod
metadata:
  name: machine_tokens
  labels:
    app: machine_tokens
spec:
  containers:
    - name: keycloak
      image: quay.io/keycloak/keycloak:latest
      command:
        - /bin/bash
        - -c
      args: 
        - /opt/keycloak/bin/kc.sh start-dev --import-realm
      ports:
        - hostPort: 4000
          containerPort: 8080
      env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
      volumeMounts:
        - mountPath: /opt/keycloak/data/import
          name: realm_import
    - name: vault
      image: docker.io/hashicorp/vault:latest
      ports:
        - hostPort: 4200
          containerPort: 8200
      env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: root
      securityContext:
        capabilities:
          add: ["IPC_LOCK"]
      volumeMounts:
        - mountPath: /init_vault.sh
          name: init_vault
    - name: mis
      image: localhost/mis:latest
      command:
        - /usr/bin/mis
      args:
        - --port=8081
        - --client_id=vault
        - --client_secret=vault
        - --username=cosmin
        - --password=cosmin
        - --server_url=http://localhost:8080
      ports:
        - hostPort: 8080
          containerPort: 8081
          
  volumes:
    - name: realm_import
      hostPath:
        path: /home/cosmin/projects/ansible/barclays/realm
        type: Directory
    - name: init_vault
      hostPath:
        path: /home/cosmin/projects/ansible/barclays/init_vault.sh
        type: File
